Attribute VB_Name = "StratificationQA"
'===============================================================
' StratificationQA
'
' Purpose: automate a pool-concentration due-diligence check on the
' "Stratification" tab produced by excel_export.export_cashflow_workbook
' (see backend/app/excel_export.py). That tab is written by openpyxl with
' headers starting at row 3: the bucket field (e.g. "property_type"),
' "total_balance", and "pool_pct". openpyxl cannot itself write VBA into
' an .xlsx it creates, so this macro is imported once into the exported
' workbook (or a macro-enabled copy of it) rather than generated by the
' Python side -- that split, not a missing feature, is why this ships as
' a separate .bas file instead of inside excel_export.py.
'
' What it does:
'   1. Reads the pool_pct column on the Stratification sheet.
'   2. Color-flags any bucket over a concentration threshold (default
'      20% = red, 10-20% = amber) -- a standard securitization
'      due-diligence check: is any single collateral bucket (property
'      type, state, FICO band, etc.) carrying an outsized share of the
'      pool.
'   3. Writes a one-line summary (count of flagged buckets, their
'      combined pool share) below the table.
'
' Usage:
'   Excel > Alt+F11 > File > Import File... > select this .bas file.
'   Run FlagConcentrationRisk from the Macro list (Alt+F8), or wire it to
'   a button via Developer > Insert > Button > assign macro.
'   Save the workbook as .xlsm to keep the macro attached.
'===============================================================
Option Explicit

Private Const SHEET_NAME As String = "Stratification"
Private Const HEADER_ROW As Long = 3
Private Const HIGH_THRESHOLD As Double = 20   ' percent
Private Const MED_THRESHOLD As Double = 10    ' percent

Private Const COLOR_HIGH As Long = 13551615   ' light red  (RGB 255,199,206)
Private Const COLOR_MED As Long = 10284031    ' light amber (RGB 255,235,156)
Private Const COLOR_OK As Long = 13561798     ' light green (RGB 198,239,206)

Sub FlagConcentrationRisk()

    Dim ws As Worksheet
    Dim lastRow As Long, lastCol As Long
    Dim pctCol As Long, balCol As Long, bucketCol As Long
    Dim r As Long
    Dim pctVal As Double
    Dim flaggedCount As Long
    Dim flaggedPct As Double
    Dim summaryRow As Long

    On Error Resume Next
    Set ws = ThisWorkbook.Worksheets(SHEET_NAME)
    On Error GoTo 0

    If ws Is Nothing Then
        MsgBox "No '" & SHEET_NAME & "' sheet found in this workbook. " & _
               "Run this after exporting a Module B workbook that includes a stratification table.", _
               vbExclamation, "StratificationQA"
        Exit Sub
    End If

    lastCol = ws.Cells(HEADER_ROW, ws.Columns.Count).End(xlToLeft).Column
    lastRow = ws.Cells(ws.Rows.Count, 1).End(xlUp).Row

    pctCol = FindColumn(ws, HEADER_ROW, lastCol, "pool_pct")
    balCol = FindColumn(ws, HEADER_ROW, lastCol, "total_balance")
    bucketCol = 1 ' bucket field is always written first (see _write_df)

    If pctCol = 0 Then
        MsgBox "Could not find a 'pool_pct' column on '" & SHEET_NAME & "'. " & _
               "This macro expects the layout written by excel_export.py.", _
               vbExclamation, "StratificationQA"
        Exit Sub
    End If

    flaggedCount = 0
    flaggedPct = 0

    For r = HEADER_ROW + 1 To lastRow
        If Trim(ws.Cells(r, bucketCol).Value) = "" Then Exit For

        pctVal = ws.Cells(r, pctCol).Value
        Dim rowRange As Range
        Set rowRange = ws.Range(ws.Cells(r, 1), ws.Cells(r, lastCol))

        If pctVal >= HIGH_THRESHOLD Then
            rowRange.Interior.Color = COLOR_HIGH
            flaggedCount = flaggedCount + 1
            flaggedPct = flaggedPct + pctVal
        ElseIf pctVal >= MED_THRESHOLD Then
            rowRange.Interior.Color = COLOR_MED
        Else
            rowRange.Interior.Color = COLOR_OK
        End If
    Next r

    ' Summary line two rows below the table
    summaryRow = lastRow + 2
    With ws.Cells(summaryRow, 1)
        .Value = "Concentration QA: " & flaggedCount & " bucket(s) at/above " & _
                 HIGH_THRESHOLD & "% of pool (combined " & Format(flaggedPct, "0.00") & "%). " & _
                 "Amber = " & MED_THRESHOLD & "-" & HIGH_THRESHOLD & "%. Run: " & Format(Now, "yyyy-mm-dd hh:nn")
        .Font.Bold = True
        .Font.Italic = True
    End With

    MsgBox "Concentration check complete. " & flaggedCount & " bucket(s) flagged red (>= " & _
           HIGH_THRESHOLD & "% of pool).", vbInformation, "StratificationQA"

End Sub

Private Function FindColumn(ws As Worksheet, headerRow As Long, lastCol As Long, headerText As String) As Long
    Dim c As Long
    For c = 1 To lastCol
        If LCase(Trim(ws.Cells(headerRow, c).Value)) = LCase(headerText) Then
            FindColumn = c
            Exit Function
        End If
    Next c
    FindColumn = 0
End Function
